---
title: "Assignment 4"
author: "David Dempsey"
date: "2023-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cluster}
library(readr)
library(ISLR)
library(tidyr)
library(factoextra)
library(flexclust)
library(tidyverse)
library(cluster)

## A
set.seed(123)
Pharm <- read_csv("C:/Users/pc/Downloads/Pharmaceuticals.csv")
head(Pharm)
Pharm1 <- Pharm[,3:11]
head(Pharm1)
Pharms <- scale(Pharm1)
head(Pharms)
wss <- (nrow(Pharms)-1)*sum(apply(Pharms,2,var))
wss
 for (i in 2:15) wss[i] <- sum(kmeans(Pharms,centers=i)$withinss)
wss
plot(1:15, wss, type="b", xlab="Number of Clusters",ylab="Total within sum of squares")
fit <- kmeans(Pharms, 5)
Pharms1 <- data.frame(Pharms, fit$cluster)
Pharms1
clusplot(Pharms, fit$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
#Using aggregate function to assess clusters
data <- aggregate(Pharms,by=list(fit$cluster),FUN=mean)
view(data)

## B
# Cluster 1 has the largest Beta, Leverage, and Revenue growth
# Cluster 2 has the largest PE Ratio, lowest profit margins and lowest Asset Turnover by far
# Cluster 3 has the smallest beta and smallest ROE
# Cluster 4 has the largest Market cap and largest ROE
# Cluster 5 has the largest Profit Margin and lowest beta Value

## C
#Because the non-numeric variables (variables 10 to 12) were excluded from the cluster formation process, we are unable to see whether there are noticable patterns within the clusters related to these variables. To explore any possible relationships within these variables, we must undertake separate analyses or use supplementary methods such as visualization or feature selection. If there is a way to do it otherwise, I am afraid I was unable to figure it out.

##D
# I would simply give them names in relation to there most noticible standout characteristic.
# Cluster 1 would be "Largest Beta"
# Cluster 2 would be "Largest PE Ratio"
# Cluster 3 would be "Smallest Beta"
# Cluster 4 would be "Largest market cap"
# Cluster 5 would be "Largest Profit Margin"

# These type of names make it easy for data analyst to quickly assess


```


