---
title: "Assignment2"
output:
  html_document: default
  pdf_document: default
  word_document: default
date: "2023-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(readr)
library(class)
UniversalBank <- read_csv("C:/Users/pc/Downloads/UniversalBank.csv")
View(UniversalBank)
library(caret)
library(ISLR)
library(dplyr)

#Rename columns with spaces as to not error select function
colnames(UniversalBank)[colnames(UniversalBank) == "Securities Account"] <- "SecuritiesAccount"
colnames(UniversalBank)[colnames(UniversalBank) == "Personal Loan"] <- "PersonalLoan"
colnames(UniversalBank)[colnames(UniversalBank) == "CD Account"] <- "CDAccount"

summary(UniversalBank)
head(UniversalBank)

#All predictors except ID and ZIP code
UniversalBank_pred <- select(UniversalBank,Age,Experience,Income,Family,CCAvg,Education,Mortgage,SecuritiesAccount,PersonalLoan,CDAccount,Online,CreditCard)

#Prep data for training and validation
set.seed(123)
train_index <- createDataPartition(UniversalBank_pred$PersonalLoan, p = 0.6, list = FALSE)
train_data <- UniversalBank_pred[train_index,]
valid_data <- UniversalBank_pred[-train_index,]

knn_model <- knn(train_data[, -12], valid_data[, -12], train_data$PersonalLoan, k =1 )
knn_model

set.seed(123)  # Set seed for reproducibility
cv <- trainControl(method = "cv", number = 5)
k_values <- seq(1, 20, by = 1)
knn_cv <- train(PersonalLoan ~ ., data = train_data, method = "knn", trControl = cv, tuneGrid = data.frame(k = k_values))

# Display the cross-validation results
View(knn_cv$results)

confusion_matrix <- table(knn_model, valid_data$PersonalLoan)

# Calculate accuracy, precision, recall, and F1-score
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
precision <- diag(confusion_matrix) / colSums(confusion_matrix)
recall <- diag(confusion_matrix) / rowSums(confusion_matrix)
f1_score <- 2 * (precision * recall) / (precision + recall)

# Display the confusion matrix and performance metrics
confusion_matrix
accuracy
precision
recall
f1_score

new_customer <- data.frame(
  Age = 40,
  Experience = 10,
  Income = 84,
  Family = 2,
  CCAvg = 2,
  Education = 1,
  Mortgage = 0,
  SecuritiesAccount = 0,
  PersonalLoan = 0,
  CDAccount = 0,
  Online = 1,
  CreditCard = 1
)

 #Classify the new customer using the best k
best_k <- knn_cv$bestTune$k
prediction <- knn(train_data[, -12], new_customer[,-12], train_data$PersonalLoan, k = best_k)

 #Display the classification result for the new customer
View(prediction)

#I've run out of time on question #5, I cannot figure it out no matter how I run it. Thank you for the added time but it was not possible for me.
```
